require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
install! 'cocoapods', :deterministic_uuids => false

# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'ZELLIT' do
  # Comment the next line ifcd  you don't want to use dynamic frameworks
  use_unimodules!
    config = use_native_modules!

    use_react_native!(:path => config["reactNativePath"])

  # Pods for ZELLIT

  target 'ZELLITTests' do
    inherit! :complete
    # Pods for testing
  end
  use_flipper!({ 'Flipper-Folly' => '2.3.0', 'Flipper-RSocket'=>'1.1' })
    post_install do |installer|
        #react_native_post_install(installer)
     flipper_post_install(installer)
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
          end
        end
    end

end

target 'ZELLIT-tvOS' do
  # Pods for ZELLIT-tvOS

  target 'ZELLIT-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
